questions = [
    'What remains after all versions of you have been dismantled?',
    'Which instincts have you suppressed to gain acceptance?',
    'How much emotional residue influences your actions?',
    'What masks do you wear, and what purpose do they serve?',
    'Can you distinguish clearly between desire and design in your life?',
    'What fears prevent you from fully expressing yourself?',
    'Who holds power over your loyalty, and why?',
    'What do you sacrifice for others without equal return?',
    'Are your connections enhancing or obstructing your clarity?',
    'Is your compassion genuinely beneficial or merely habitual?',
    'How often is your kindness transactional?',
    'When does truth become a resource rather than a pursuit for you?',
    'What aspects of your identity have been shaped by others’ perceptions?',
    'Which virtues are actually liabilities in your life?',
    'In what ways do you exploit cognitive weaknesses of others?',
    'Do you genuinely care, or do you perform care strategically?',
    'What truths have you withheld for personal advantage?',
    'How efficiently can you detach from emotional attachments?',
    'Which of your relationships have become purely transactional?',
    'Are you genuinely strong or merely performing strength?',
    'What desires have you internalised as shameful?',
    'How often do you minimise your presence to accommodate others?',
    'Is your identity shaped more by pain or by joy?',
    'Have you mistaken endurance for personal identity?',
    'What part of your life feels chronically empty or detached?',
    'Can you express love without expecting it to turn into loss?',
    'Why does peace feel suspicious to you?',
    'Are you addicted to pain as a source of creative drive?',
    'Can you engage in relationships without scripting interactions?',
    'Do you fear rejection or misunderstanding more?',
    'How much of your life do you live as an observer rather than participant?',
    'What vulnerabilities do you refuse to acknowledge openly?',
    'Are you withholding from intimacy out of self-protection or fear of exposure?',
    'Does your internal scaffolding feel threatened by genuine connection?',
    'What emotional selves have you buried to survive?',
    'What aspects of yourself are you afraid others might reduce or misunderstand?',
    'Are you truly present in your relationships or lost in self-analysis?',
    'Can you act authentically without certainty?',
    'Are you waiting for permission to live your own life?',
    'What thresholds have you avoided crossing out of fear?',
    'What anger have you suppressed and why?',
    'What truths have you ignored out of loyalty to others?',
    'In what ways have you betrayed yourself to maintain peace?',
    'How much of your anger comes from neglecting yourself?',
    'Are you being small to fit into roles you don’t believe in?',
    'What parts of yourself have you left neglected?',
    'Is your loyalty primarily directed inward or outward?',
    'How long have you been deferring your needs to accommodate others?',
    'Are you living in quiet rage because of unmet expectations?',
    'What would it look like to embrace your anger positively?',
    'How do you silence your own desires?',
    'Do you view your anger as destructive or illuminating?',
    'What truths do you fear acknowledging about yourself?',
    'Have you genuinely committed to self-loyalty, or is it conditional?',
    'Can you honour your needs without external validation?',
    'Do you see your anger as a force for growth or something to avoid?',
    'What boundaries have you neglected to set?',
    'Are your relationships rooted in genuine self-expression or self-censorship?',
    'What emotional debts are you carrying?',
    'How does your anger manifest physically within you?',
    'Do you seek comfort or truth in your reflections?',
    'Are you genuinely engaging with reality or hiding behind ideologies?',
    'What illusions are you most reluctant to let go of?',
    'What parts of your reality do you intentionally ignore?',
    'Are you trapped in abstract thought or actively living your truths?',
    'What does true self-awareness look like for you?',
    'How do you handle ruptures in your perceived self?',
    'Are you seeking neat answers or deeper understanding?',
    'Do you accept ambiguity as part of your reality?',
    'What contradictions shape your life?',
    'How do you define personal growth beyond romantic relationships?',
    'Are your heartbreaks evolving you or trapping you?',
    'What is your primary cathartic practice?',
    'How much of your identity is fluid versus fixed?',
    'What path have you chosen out of dissatisfaction?',
    'Are you a passive observer or an active creator in your life?',
    'What does genuine curiosity look like to you?',
    'What identity have you built purely out of defence mechanisms?',
    'What core beliefs are you most reluctant to challenge?',
    'Are your daily actions aligned with your self-claimed truths?',
    'What cognitive patterns trap you in repetitive cycles?',
    'What emotional reactions do you default to when challenged?',
    'How do you measure your self-worth beyond external validation?',
    'Which fears are currently dictating your life choices?',
    'Are you genuinely expressing your intensity or suppressing it?',
    'What deeper needs are masked by your surface desires?',
    'Do your relationships genuinely nourish or drain you?',
    'Are you genuinely present in the now, or always mentally elsewhere?',
    'Can you sustain stillness without suspicion or discomfort?',
    'What emotional states do you actively avoid confronting?',
    'Which coping mechanisms have become outdated in your life?',
    'What emotional debts do you owe yourself?',
    'Which internal dialogues consistently limit your potential?',
    'Are your motivations genuine or performative?',
    'What emotional truths are hardest for you to accept about yourself?',
    'How often do you betray your intuition for social acceptance?',
    'Do you genuinely believe you deserve fulfilment?',
    'What roles have you adopted purely to maintain control?',
    'Are you more committed to self-discovery or self-preservation?',
    'What personal truths have you commodified or diluted for others?',
     "What mechanisms of performance are controlling your life?",
        "Which past versions of yourself do you still pretend to be?",
        "When has empathy acted against your best interests?",
        "What connections have you maintained out of habit rather than purpose?",
        "Are you genuinely autonomous or controlled by hidden fears?",
        "How often do you act without hesitation?",
        "What would genuine internal loyalty look like for you?",
        "Which ambitions have you shamed into silence?",
        "Are you truly aligned with your goals or merely pursuing desires?",
        "What sacrifices are you making without equal return?",
        "Can you live without emotional approval from others?",
        "What aspects of your identity have you commodified?",
        "Are you functioning optimally or simply performing competence?",
        "Which societal myths are you clinging to despite knowing better?",
        "What truths about yourself have you intentionally dressed up?",
        "What relationships are based purely on transactional value?",
        "How much of your daily life is dedicated to authentic self-expression?",
        "Which part of you acts efficiently and without emotional residue?",
        "Is your compassion truly optional or secretly obligatory?",
        "When do you pretend to care, and why?",
        "What deeper shame prevents you from fully occupying your life?",
        "Why do you apologise for your intensity?",
        "Are you mistaking denial for strength?",
        "How often are you detached from your own lived experiences?",
        "Do you trust yourself to genuinely act from love?",
        "Is pain your primary source of creative energy?",
        "Can you build from safety or only from wreckage?",
        "Why does peace make you suspicious?",
        "What vulnerabilities are you unwilling to express openly?",
        "Do you prefer being misunderstood to risking genuine openness?",
        "Are you afraid of proximity destroying your curated identity?",
        "What emotional parts of you are still buried beneath survival strategies?",
        "Do you love without over-explaining yourself?",
        "Are you truly willing to reclaim your right to vulnerability?",
        "Can you embrace uncertainty without self-sabotage?",
        "Is your presence genuine or a performed version of yourself?",
        "What unresolved emotions still influence your current relationships?",
        "Can you trust others without skepticism or hidden doubts?",
        "Do you hesitate out of true caution or habit?",
        "Are you honest about your deepest fears?",
        "What is your silent anger demanding you acknowledge?",
        "Have you made yourself small to preserve someone else’s peace?",
        "Can you fully accept yourself without external validation?",
        "What emotional lies have you told yourself repeatedly?",
        "Are you betraying your own growth by prioritising others’ comfort?",
        "What does genuine self-loyalty look like to you practically?",
        "Have you defined yourself more through trauma or clarity?",
        "What neglected part of yourself do you owe an apology?",
        "Do you fear fully inhabiting your power?",
        "How would you behave if fear of judgment ceased entirely?",
        "What would genuine authenticity feel like physically for you?",
        "Which parts of your identity have you sacrificed for societal norms?",
        "Can you be unapologetically yourself without guilt?",
        "Is your anger primarily destructive or productive?",
        "Have you conflated patience with suppression?",
        "Can you face your shadows without self-condemnation?",
        "What neglected truth about yourself must you confront urgently?",
        "How do you betray your own emotional truths?",
        "Can you truly forgive yourself for past betrayals of self?",
        "Are you honest about your anger, or do you intellectualise it?",
        "Which norms and ideologies are you hiding behind?",
        "Can you face reality without sentimentality or abstraction?",
        "Do you use philosophical thought as escape or confrontation?",
        "Which illusions comfort you more than the truth?",
        "Can you live fully aware of your contradictions?",
        "Have you labeled your experiences inaccurately for comfort?",
        "Do you see your emotional pain as a growth tool or burden?",
        "What identities are you trying to reconcile within yourself?",
        "Which boundaries between yourself and society do you constantly blur?",
        "Can you authentically exist without a clearly defined path?",
        "What cyclical patterns have you failed to break within yourself?",
        "Are you honest about your motives when seeking connection?",
        "Do you live predominantly in the past, future, or present?",
        "What emotional debts to yourself remain unpaid?",
        "Can you act decisively without emotional compromise?",
        "How much of your daily life reflects genuine curiosity?",
        "What emotional narratives do you perpetually repeat?",
        "Are you cultivating a meaningful life or just surviving?",
        "Do you openly acknowledge your capacity for harm?",
        "What truths are you avoiding because they are uncomfortable?",
        "What balance between empathy and detachment do you genuinely maintain?",
        "Which virtues in your life have turned into liabilities?",
        "How does unresolved anger influence your current actions?",
        "Which connections drain you more than they sustain you?",
        "Can you be kind without expecting any return?",
        "Have you allowed others to define your personal truths?",
        "Do you trust your intuitive reactions completely?",
        "Are you truly living or just managing existence?",
        "How much emotional energy is tied up in past regrets?",
        "Can you embrace vulnerability without losing power?",
        "What personal values do you compromise to maintain peace?",
        "Do your relationships reflect your genuine self or an adaptation?",
        "Are you actively contributing to your own emotional stagnation?",
        "Can you let go of the comfort of old emotional patterns?",
        "What false narratives have you created about yourself?",
        "Do you seek truth primarily externally or internally?",
        "What behaviours have you normalised that undermine your growth?",
        "Can you act from clarity rather than emotional habit?",
        "Are your most profound truths shared openly or hidden privately?",
        "Do you see your contradictions as obstacles or opportunities?",
    ]